[package]
name = "tiny_http"
version = "0.1.0"
authors = ["pierre.krieger1708@gmail.com",
           "Corey Farwell <coreyf@rwell.org>"]
description = "Low level HTTP server library"
license = "Apache-2.0"
repository = "https://github.com/frewsxcv/tiny-http"

[dependencies]
ascii = "0.5"
chunked_transfer = "0.3"
encoding = "0.2"
rustc-serialize = "0.3"
url = "0.2"
