[package]

name = "tiny_http"
version = "0.0.1"
authors = ["pierre.krieger1708@gmail.com", "coreyf@rwell.org"]

[dependencies]
ascii = "0.4"
rust-crypto = "*"
encoding = "0.2"
rustc-serialize = "*"
url = "0.2"
